elchininet/postcss-rtlcss

CHANGELOG.md, README.md, src/index.ts, src/rules/parser.ts, src/rules/rules-combined.ts, src/rules/rules-override.ts, src/utilities/comments.ts, src/utilities/rules.ts, tests/__snapshots__/combined.test.ts.snap, tests/__snapshots__/override.test.ts.snap
- Improve the output formatting
- Refactored multiple utility methods to make them simpler
- Created a CHANGELOG
=> Multiple changes

CHANGELOG.md, README.md, src/@types/index.ts, src/data/shorthands.json, src/parsers/declarations.ts, src/utilities/options.ts, src/utilities/rules.ts, src/utilities/shorthands.ts, tests/__snapshots__/combined.test.ts.snap, tests/__snapshots__/override.test.ts.snap, tests/combined.test.ts, tests/css/input.css, tests/override.test.ts, tsconfig.json
=> Add a bothPrefix option to manage overridden properties due to specificity

CHANGELOG.md, src/index.ts, src/parsers/atrules.ts, src/parsers/declarations.ts, tests/__snapshots__/combined.test.ts.snap, tests/__snapshots__/override.test.ts.snap, tests/css/input.css
=> Fix a bug that was preventing animation name flipping in names surrounded by commas

src/index.ts, src/parsers/atrules.ts, src/parsers/declarations.ts, src/parsers/rules.ts, src/utilities/containers.ts, src/utilities/directives.ts, tests/__snapshots__/combined-autorename.test.ts.snap, tests/__snapshots__/combined-basic-options.test.ts.snap, tests/__snapshots__/combined-prefixes.test.ts.snap, tests/__snapshots__/combined-string-map.test.ts.snap, tests/__snapshots__/override-autorename.test.ts.snap, tests/__snapshots__/override-basic-options.test.ts.snap, tests/__snapshots__/override-prefixes.test.ts.snap, tests/__snapshots__/override-string-map.test.ts.snap, tests/css/input.css
To prepare the plugin to manage other control directives, it is necessary to move the logic about control directive detection outside of the WalkContainer utility, so, the directives will be managed separated for each parser.
=> Move the logic of directive detection outside of the walkcontainer utility

CHANGELOG.md, README.md, src/constants/index.ts, src/parsers/declarations.ts, src/parsers/rules.ts, src/utilities/directives.ts, tests/__snapshots__/combined-autorename.test.ts.snap, tests/__snapshots__/combined-basic-options.test.ts.snap, tests/__snapshots__/combined-prefixes.test.ts.snap, tests/__snapshots__/combined-string-map.test.ts.snap, tests/__snapshots__/override-autorename.test.ts.snap, tests/__snapshots__/override-basic-options.test.ts.snap, tests/__snapshots__/override-prefixes.test.ts.snap, tests/__snapshots__/override-string-map.test.ts.snap, tests/css/input.css
This directive parses the `CSS` parameter and inserts it in its place. Depending on the `source` parameter the parsed `CSS` will be treated as `rtl` or `ltr`:
```css
.test1 {
color: #EFEFEF;
left: 10px;
/*rtl:raw:
height: 50px;
width: 100px;*/
}
/*rtl:raw:.test2 {
color: #EFEFEF;
left: 10px;
width: 100%;    
}
.test3 {
transform: translate(10px, 20px);
}
*/
```
```css
.test1 {
color: #EFEFEF;
}
[dir="ltr"] .test1 {
left: 10px;
}
[dir="rtl"] .test1 {
right: 10px;
height: 50px;
width: 100px;
}
[dir="rtl"] .test2 {
color: #EFEFEF;
left: 10px;
width: 100%;    
}
[dir="rtl"] .test3 {
transform: translate(10px, 20px);
}
```
=> This commit implements the RTL raw control directive

README.md
The Webpack configuration example in the README file was pointing in an old configuration and with a wrong usage of the package.
This merge request fixes this.
=> Fix Webpack configuration in the README file

CHANGELOG.md, src/parsers/declarations.ts, src/parsers/rules.ts, src/utilities/rules.ts, src/utilities/selectors.ts, tests/__snapshots__/combined-nested-rules.test.ts.snap, tests/__snapshots__/override-nested-rules.test.ts.snap, tests/combined-nested-rules.test.ts, tests/css/input-nested.scss, tests/override-nested-rules.test.ts
This merge request adds support for nested rules:
```scss
.selector-1 {
left: 10px;
&.selector-2 {
color: black;
margin-left: 20px;
}
&.selector-3 {
padding: 5px;
span {
}
}
}
```
```scss
.selector-1 {
&.selector-2 {
color: black;
}
&.selector-3 {
padding: 5px
}
}
[dir="ltr"] .selector-1 {
left: 10px;
&.selector-2 {
margin-left: 20px;
}
&.selector-3 {
span {
}
}
}
[dir="rtl"] .selector-1 {
right: 10px;
&.selector-2 {
margin-right: 20px;
}
&.selector-3 {
span {
}
}
}
```
```scss
.selector-1 {
left: 10px;
&.selector-2 {
color: black;
margin-left: 20px;
}
&.selector-3 {
padding: 5px;
span {
}
}
}
[dir="rtl"] .selector-1 {
left: auto;
right: 10px;
&.selector-2 {
margin-left: 0;
margin-right: 20px;
}
&.selector-3 {
span { …
```
=> Add support for nested rules

CHANGELOG.md, package.json, src/parsers/declarations.ts, src/utilities/declarations.ts, tests/__snapshots__/combined-autorename.test.ts.snap, tests/__snapshots__/combined-basic-options.test.ts.snap, tests/__snapshots__/combined-prefixes.test.ts.snap, tests/__snapshots__/combined-safe-prefix.test.ts.snap, tests/__snapshots__/combined-string-map.test.ts.snap, tests/__snapshots__/override-autorename.test.ts.snap, tests/__snapshots__/override-basic-options.test.ts.snap, tests/__snapshots__/override-prefixes.test.ts.snap, tests/__snapshots__/override-safe-prefix.test.ts.snap, tests/__snapshots__/override-string-map.test.ts.snap, tests/css/input.css
This pull request fixes a bug when the same declaration property is declared multiple times in a rule.
```css
.test {
color: red;
text-align: center;
}
```
```css
.test {
color: red;
text-align: center;
}
[dir="ltr"] .test {
}
[dir="rtl"] .test {
}
```
> In the original CSS file the `text-align: center` is overriding the `text-align: left` but in the output, the opposite occurs due to a higher specificity of the `[dir="ltr"]` and `[dir="rtl"]` rules.
```css
.test {
color: red;
}
[dir="ltr"] .test {
}
[dir="rtl"] .test {
}
[dir] .test {
text-align: center;
}
```
> The `bothPrefix` property has been used to create a rule and maintain the same input behavior.
=> Fix multiple declarations overriding order

CHANGELOG.md, src/constants/index.ts, src/utilities/selectors.ts, tests/__snapshots__/combined-autorename.test.ts.snap, tests/__snapshots__/combined-basic-options.test.ts.snap, tests/__snapshots__/combined-prefixes.test.ts.snap, tests/__snapshots__/combined-safe-prefix.test.ts.snap, tests/__snapshots__/combined-string-map.test.ts.snap, tests/__snapshots__/override-autorename.test.ts.snap, tests/__snapshots__/override-basic-options.test.ts.snap, tests/__snapshots__/override-prefixes.test.ts.snap, tests/__snapshots__/override-safe-prefix.test.ts.snap, tests/__snapshots__/override-string-map.test.ts.snap, tests/css/input.css
For rules containing `:root` and `html` the output was wrong:
```css
:root {
}
html .test50 {
color: red;
left: 10px;
}
```
```css
[dir="ltr"] :root {
}
[dir="rtl"] :root {
}
html .test50 {
color: red;
}
[dir="ltr"] html .test50 {
left: 10px;
}
[dir="rtl"] html .test50 {
right: 10px;
}
```
```css
[dir="ltr"]:root {
}
[dir="rtl"]:root {
}
html .test50 {
color: red;
}
html[dir="ltr"] .test50 {
left: 10px;
}
html[dir="rtl"] .test50 {
right: 10px;
}
```
=> Fix a bug with :root and html rules

CHANGELOG.md, README.md, src/@types/index.ts, src/constants/index.ts, src/data/store.ts, src/parsers/rules.ts, src/utilities/selectors.ts, tests/__snapshots__/combined-prefixed.test.ts.snap, tests/__snapshots__/override-prefixed.test.ts.snap, tests/combined-prefixed.test.ts, tests/css/input-prefixed.css, tests/override-prefixed.test.ts
This pull request adds a new option to ignore rules already prefixed:
```css
[dir="ltr"] test {
left: 10px;
}
[dir="rtl"] test {
right: 10px;
}
```
```javascript
const options = { ignorePrefixedRules: true }; // This is the default value
```
```css
[dir="ltr"] test {
left: 10px;
}
[dir="rtl"] test {
right: 10px;
}
```
```javascript
const options = { ignorePrefixedRules: false };
```
```css
[dir="ltr"] [dir="ltr"] test {
left: 10px;
}
[dir="rtl"] [dir="ltr"] test {
right: 10px;
}
[dir="ltr"] [dir="rtl"] test {
right: 10px;
}
[dir="rtl"] [dir="rtl"] test {
left: 10px;
}
```
=> Add a new option to ignore rules already prefixed

CHANGELOG.md, README.md, package.json, src/@types/index.ts, src/data/store.ts, src/parsers/declarations.ts, tests/__snapshots__/combined-aliases.test.ts.snap, tests/__snapshots__/override-aliases.test.ts.snap, tests/combined-aliases.test.ts, tests/css/input-variables.css, tests/override-aliases.test.ts, tests/tests-constants.ts, yarn.lock
This pull request solves https://github.com/elchininet/postcss-rtlcss/issues/65
This property consists of a string map to treat some declarations as others, very useful to flip the values of [CSS variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)
```css
:root {
--my-padding: 1rem 1rem 1.5rem 1.5rem;
}
.test {
padding: var(--my-padding);
}
```
```css
:root {
--my-padding: 1rem 1rem 1.5rem 1.5rem;
}
.test {
padding: var(--my-padding);
}
```
```javascript
const options = {
aliases: {
'--my-padding': 'padding'
}
};
```
```css
[dir="ltr"]:root {
--my-padding: 1rem 1rem 1.5rem 1.5rem;
}
[dir="rtl"]:root {
--my-padding: 1rem 1.5rem 1.5rem 1rem;
}
.test {
padding: var(--my-padding);
}
```
=> Add a new option to support declarations aliases

CHANGELOG.md, src/utilities/rules.ts, tests/__snapshots__/nested-rules.test.ts.snap, tests/css/input-nested.scss
This pull request fixes a bug that was removing rules without declarations but with at-rules inside.
This code:
```scss
.b-product-single {
&__main {
@media screen and (min-width: 991px) {
display: grid;
grid-template-columns: 1fr 250px;
grid-column-gap: var(--large-margin);
}
}
&__image-wrapper {
overflow: hidden;
img {
max-width: 100%;
height: auto;
object-fit: scale-down;
}
}
}
```
Was converted to:
```scss
.b-product-single {
&__image-wrapper {
overflow: hidden;
img {
max-width: 100%;
height: auto;
object-fit: scale-down;
}
}
}
[dir="ltr"] .b-product-single {
&__image-wrapper {
text-align: right
}
}
[dir="rtl"] .b-product-single {
&__image-wrapper {
text-align: left
}
}
```
Removing the `&__main` rule.
After this fix, the result will be:
```scss
.b-product-single { …
```
=> Fix a bug that was removing rules without declarations but with atRules

CHANGELOG.md, README.md, src/@types/index.ts, src/data/store.ts, src/index.ts, src/parsers/atrules.ts, src/parsers/declarations.ts, src/parsers/rules.ts, src/utilities/clean.ts, src/utilities/rules.ts, tests/__snapshots__/autorename.test.ts.snap, tests/__snapshots__/basic-options.test.ts.snap, tests/__snapshots__/nested-rules.test.ts.snap, tests/__snapshots__/noflip.test.ts.snap, tests/__snapshots__/prefixed.test.ts.snap, tests/__snapshots__/prefixes.test.ts.snap, tests/__snapshots__/safe-prefix.test.ts.snap, tests/__snapshots__/string-map.test.ts.snap, tests/__snapshots__/variables.test.ts.snap, tests/utils/index.ts
The new `diff` mode allows to generate the minimum amount of code because it only outputs the rules that have been flipped and without prefixing them. The intention of this method is to generate a separate stylesheet file that will be loaded on top of the original one to override those rules that need to be flipped in certain direction.
>**Note:** This method has [the same disadvantage](https://github.com/elchininet/postcss-rtlcss#output-using-the-override-mode) of using the `override` method.
```css
.test1, .test2 {
background-color: #FFF;
background-position: 10px 20px;
border-radius: 0 2px 0 8px;
color: #666;
padding-right: 20px;
transform: translate(-50%, 50%);
width: 100%;
}
.test3 {
direction: ltr;
margin: 1px 2px 3px;
padding: 10px 20px;
text-align: center;
}
``` …
=> Introduce a new mode to generate only flipped rules

CHANGELOG.md, src/parsers/declarations.ts, tests/__snapshots__/safe-prefix.test.ts.snap
This pull request solves an issue in `diff` mode when the options `safeBothPrefix` and `processKeyFrames` are enable at the same time. In these conditions, the next CSS code:
```css
.test {
animation: 5s flip 1s ease-in-out,
3s my-animation 6s ease-in-out;
}
@keyframes flip {
from {
transform: translateX(100px);
}
to {
transform: translateX(0);
}
}
```
was being transformed as:
```css
.test {
animation: 5s flip-ltr 1s ease-in-out,
3s my-animation 6s ease-in-out;
animation: 5s flip-rtl 1s ease-in-out,
3s my-animation 6s ease-in-out;
}
@keyframes flip-ltr {
from {
transform: translateX(-100px);
}
to {
transform: translateX(0);
}
}
```
Note the double `animation` property repeating the declaration that should be overriden.
=> Fix a bug with safeBothPrefix and processKeyFrames options in diff mode

package.json, yarn.lock
[After fixing](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60454) the `processEnv` option, the `@types/rtlcss` package can be upgrade without errors.
=> Update RTCSS types

.gitignore, CHANGELOG.md, src/data/logical-declarations.json, src/utilities/declarations.ts
This pull request applies the `safeBothPrefix` to logical declarations overridden by physical ones.
```css
.test {
padding-right: 20px;
padding-inline-end: 30px;
}
```
Note that `padding-inline-end` is being overridden by `padding-right` or `padding-left` depending on the direction.
```css
.test {
padding-inline-end: 30px;
}
[dir="ltr"] .test {
padding-right: 20px;
}
[dir="rtl"] .test {
padding-left: 20px;
}
```
```css
[dir="ltr"] .test {
padding-right: 20px;
}
[dir="rtl"] .test {
padding-left: 20px;
}
[dir] .test {
padding-inline-end: 30px;
}
```
=> Apply the safe prefix to logical declarations overridden by physical ones

CHANGELOG.md, README.md, src/@types/index.ts, src/constants/index.ts, src/data/store.ts, src/utilities/selectors.ts, tests/__snapshots__/prefixes.test.ts.snap, tests/prefixes.test.ts
This pull request adds a new option to transform the prefixing logic of the selectors at our will.
This function will be used to transform the selectors and prefixing them at our will. The first parameter will be the prefix that will be used and the second the current selector:
>Notes:
>* If the function doesn‘t return a string, the default prefixing logic will be used.
>* If this function is used, be aware that rules using `html` or `:root` will follow the custom prefixing logic. You should cover these cases.
```css
.test1 {
left: 10px;
padding-right: 5px;
padding-inline-end: 20px;
}
```
If the `prefixSelectorTransformer` is not sent (default):
```css
[dir="ltr"] .test1 {
left: 10px;
padding-right: 5px;
}
[dir="rtl"] .test1 {
right: 10px;
padding-left: 5px;
}
[dir] .test1 { …
```
=> Add an option to have more control over the selector prefixing logic

CHANGELOG.md, src/@types/index.ts, src/parsers/declarations.ts, src/utilities/declarations.ts, tests/__snapshots__/autorename.test.ts.snap, tests/__snapshots__/basic-options.test.ts.snap, tests/__snapshots__/overriding.test.ts.snap, tests/__snapshots__/prefixes.test.ts.snap, tests/__snapshots__/safe-prefix.test.ts.snap, tests/__snapshots__/string-map.test.ts.snap, tests/css/overriding.css, tests/overriding.test.ts
This merge request improves the overriding logic to cover multiple cases in which it was failing due to multiple overrides.
Previously, this input:
```css
.test {
text-align: center;
}
```
Was converted to:
```css
[dir="ltr"] .test {
}
[dir="rtl"] .test {
}
[dir] .test {
text-align: center;
}
```
But there is no need to convert that input, the `text-align` property has been overridden by a property that doesn‘t have an `rtl` counterpart, so it should not be modified.
Previously, this input:
```css
.test1 {
padding-right: 8px;
padding-left: 8px;
padding-left: 0;
padding-right: 0;
}
```
Was converted to:
```css
.test1 {
padding-left: 0;
padding-right: 0;
}
[dir="ltr"] .test1 {
padding-right: 8px;
padding-left: 8px;
}
[dir="rtl"] .test1 …
```
=> Improve declaration overriding logic

CHANGELOG.md, README.md, package.json, tests/__snapshots__/autorename.test.ts.snap, tests/__snapshots__/basic-options.test.ts.snap, tests/__snapshots__/nested-rules.test.ts.snap, tests/__snapshots__/overriding.test.ts.snap, tests/__snapshots__/prefixed.test.ts.snap, tests/__snapshots__/prefixes.test.ts.snap, tests/__snapshots__/safe-prefix.test.ts.snap, tests/__snapshots__/string-map.test.ts.snap, tests/__snapshots__/variables.test.ts.snap, yarn.lock
This `RTLCSS` version brings these changes:
* Support flipping `justify-content`, `justify-items` and `justify-self`
* Support flipping length background position without using `calc`
```css
.test {
background-position: 10px 20px;
justify-content: left;
justify-items: right; 
justify-self: left;
}
```
```css
.test {
background-position: right 10px top 20px;
justify-content: right;
justify-items: left;
justify-self: right;
}
```
=> Upgrade RTLCSS to major version 4.0.0

CHANGELOG.md, src/@types/index.ts, src/parsers/declarations.ts, src/utilities/declarations.ts, tests/__snapshots__/overriding.test.ts.snap, tests/css/overriding.css
This pull request solves a bug related to overridden declarations. Previously, if a rule contained overridden declarations, only the last one was taken into account:
<table>
<thead>
<tr>
<th>Input</th>
<th>Output</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<pre>
<code>.test {
padding: 0 2px 0 4px;
padding: 0 4px 0 8px;
padding: 0 8px 0 16px;
}</code>
</pre>
</td>
<td>
<pre>
<code>.test {
padding: 0 2px 0 4px;
padding: 0 4px 0 8px;
}
[dir="ltr"] .test {
padding: 0 8px 0 16px;
}
[dir="rtl"] .test {
padding: 0 16px 0 8px;
}</code>
</pre>
</td>
</tr>
</tbody>
</table>
But this is problematic with declarations that flip their property instead of their value:
<table>
<thead>
<tr>
<th>Input</th>
<th>Output</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<pre>
<code>.test {
margin-left: 1px;
margin-left: 2px; …
=> Fix a bug related to overridden declarations

.github/workflows/deploy.yaml, scripts/extract_last_release_body.js
This pull request implements a Github job in the deploy action to create a Github release after a successful NPM deployment.
Closes #192
=> Create Github releases after a successful NPM deployment

CHANGELOG.md, src/index.ts, src/utilities/clean.ts, tests/__snapshots__/empty-rules.test.ts.snap, tests/css/empty-rules.css, tests/empty-rules.test.ts
This pull request fixes the unwanted deletion of empty rules. The plugin should clean the rules that are empty due to its internal process, but should not clean the rules that were there empty in the original CSS file, if a user wants to clean those rules, they should use another `postcss` plugin for that purpose. Cleaning empty CSS rules is out of the scope of this plugin.
Closes #190
=> Avoid removing empty rules

.github/workflows/deploy.yaml
In a release, assets should have unique names. CommonJS and ESM assets have the same name and this was creating an issue with the assets uploader action. This pull request adds only the ESM bundles to the assets.
=> Upload only esm bundles

CHANGELOG.md, src/utilities/rules.ts, tests/__snapshots__/nested-rules.test.ts.snap, tests/css/input-nested.scss
AtRules used by some plugins/libraries to create mixins, do not have children. E.g:
```scss
@include some-mixin;
```
This was provoking an error with CSS code with these kind of rules:
>Cannot read properties of undefined (reading 'some')
This pull request fixes this issue
Closes #204
=> Fix an error related to empty atRules

CHANGELOG.md, package.json, yarn.lock
This pull request updates [RTLCSS](https://rtlcss.com/) to version `4.1.0`.
=> Update RTLCSS to version 4.1.0

README.md
This pull request does a small correction in the documentation to make it clear that the override method lets the main rule intact "most of the time".
=> Small correction on documentation

.github/workflows/deploy.yaml, CHANGELOG.md, package.json, scripts/copy.sh
Following the recommendations in the [TypeScript Handbook](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing). This is to avoid `TypeScript` complaining about missing types when the ESM module is used:
>Could not find a declaration file for module 'postcss-rtlcss'. '/path-to-project/node_modules/postcss-rtlcss/esm/index.js' implicitly has an 'any' type.
There are types at '/path-to-project/node_modules/postcss-rtlcss/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'postcss-rtlcss' library may need to update its package.json or typings.ts(7016)
=> Fix ESM types

src/data/logical-declarations.json, tests/__snapshots__/autorename.test.ts.snap, tests/__snapshots__/basic-options.test.ts.snap, tests/__snapshots__/prefixes.test.ts.snap, tests/__snapshots__/safe-prefix.test.ts.snap, tests/__snapshots__/string-map.test.ts.snap, tests/css/input.css
This pull request adds `margin-block`, `margin-block-start`, `margin-block-end`, `padding-block`, `padding-block-start` and `padding-block-end` to the logical declarations that can be overridden by `margin` and `padding` respectively. This adds these declarations to the ones affected by `safeBothPrefix` option.
Closes #222.
=> Add margin-block and padding-block properties to logical declarations override

src/@types/index.ts
The enum values types were using the enums' keys just because the keys and the values were the same, but it is better to get the string representation of the enums that returns the exact values.
```typescript
enum Mode {
combined = 'combined',
override = 'override',
diff = 'diff'
}
```
```typescript
// Before
type ModeValues = keyof typeof Mode; // 'combined' | 'override' | 'diff'
// After
type ModeValues = `${Mode}`; // 'combined' | 'override' | 'diff'
```
=> Refactor enum values types

CHANGELOG.md
Version `5.0.0` will be released today (December 30th 2023), so changing the date in the changelog.
=> Change CJANGELOG release date

.github/workflows/deploy.yaml
This pull request adds [the --provenance flag](https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions) to the `npm publish` command in the deploy workflow.
=> Publish the package using npm provenance

CHANGELOG.md, README.md, src/constants/index.ts, src/parsers/declarations.ts, src/parsers/rules.ts, tests/__snapshots__/basic-options.test.ts.snap, tests/__snapshots__/prefixes.test.ts.snap, tests/__snapshots__/string-map.test.ts.snap, tests/css/input.css
This pull request implements new directives to control the [processRuleNames option](https://github.com/elchininet/postcss-rtlcss?tab=readme-ov-file#processrulenames).
This directive set the `processRuleNames` option to `true` in the next rule no mattering the value of the global `processRuleNames` option:
```css
/*rtl:rules*/
.test1-ltr {
background-image: url('/images/test1-l.png');
}
/*rtl:rules*/
.test1-rtl {
background-image: url('/images/test1-r.png');
}
/*rtl:rules*/
.test2-left::before {
content: "\f007";
}
.test2-right::before {
content: "\f010";
}
```
```css
[dir="ltr"] .test1-ltr {
background-image: url('/images/test1-l.png');
}
[dir="rtl"] .test1-ltr {
background-image: url('/images/test1-r.png');
}
[dir="ltr"] .test1-rtl {
background-image: url('/images/test1-r.png');
} …
```
=> Implement new directives to control processRuleNames option

.github/workflows/deploy.yaml
During the migration to pnpm the registry-url parameter of the Node set up step was removed. This pull request restores it.
=> Restore Set up node registry url

README.md
This PR only fixes a small typo in the README file: 'PostcCSS' → 'PostCSS'.
=> Fix 'PostcCSS' → 'PostCSS' typo in README

src/parsers/declarations.ts, tests/__snapshots__/aliases-custom-declarations/combined/no-aliases-safe-both-prefix-false.snapshot, tests/__snapshots__/aliases-custom-declarations/combined/no-aliases-safe-both-prefix-true.snapshot, tests/__snapshots__/aliases-custom-declarations/combined/with-aliases-safe-both-prefix-false.snapshot, tests/__snapshots__/aliases-custom-declarations/combined/with-aliases-safe-both-prefix-true.snapshot, tests/__snapshots__/aliases-custom-declarations/diff/no-aliases-safe-both-prefix-false.snapshot, tests/__snapshots__/aliases-custom-declarations/diff/no-aliases-safe-both-prefix-true.snapshot, tests/__snapshots__/aliases-custom-declarations/diff/with-aliases-safe-both-prefix-false.snapshot, tests/__snapshots__/aliases-custom-declarations/diff/with-aliases-safe-both-prefix-true.snapshot, tests/__snapshots__/aliases-custom-declarations/override/no-aliases-safe-both-prefix-false.snapshot, tests/__snapshots__/aliases-custom-declarations/override/no-aliases-safe-both-prefix-true.snapshot, tests/__snapshots__/aliases-custom-declarations/override/with-aliases-safe-both-prefix-false.snapshot, tests/__snapshots__/aliases-custom-declarations/override/with-aliases-safe-both-prefix-true.snapshot, tests/aliases-custom-declarations.test.ts, tests/constants/index.ts, tests/css/input-aliases.css
This pull request makes aliases being taken into account for both-prefixed and safe-prefixed declarations. In this way if a declaration needs to be moved to a prefixed rule with the `bothPrefix`, either because it can be overriden or because the `safeBothPrefix` rule is set, it will do the same with an alias of such a declaration.
=> Make aliases affect both-prefixed and safe-prefixed declarations

src/data/store.ts, src/parsers/atrules.ts, src/parsers/declarations.ts, src/parsers/rules.ts, src/utilities/clean.ts, src/utilities/containers.ts, src/utilities/declarations.ts, src/utilities/predicates.ts, src/utilities/rules.ts, src/utilities/selectors.ts
This pull request simplifies the code to check for the `postcss` node types and the typeof of multiple variables using `TypeScript` predicates.
=> Simplify type checking using predicates

CHANGELOG.md, src/@types/index.ts, src/data/store.ts, src/parsers/atrules.ts, src/parsers/declarations.ts, src/parsers/rules.ts, src/utilities/clean.ts, src/utilities/declarations.ts, src/utilities/predicates.ts, src/utilities/rules.ts, tests/__snapshots__/nested-rules/combined/source-ltr-process-rule-names-true.snapshot, tests/__snapshots__/nested-rules/combined/source-ltr.snapshot, tests/__snapshots__/nested-rules/combined/source-rtl-process-rule-names-true.snapshot, tests/__snapshots__/nested-rules/combined/source-rtl.snapshot, tests/__snapshots__/nested-rules/diff/source-ltr-process-rule-names-true.snapshot, tests/__snapshots__/nested-rules/diff/source-ltr.snapshot, tests/__snapshots__/nested-rules/diff/source-rtl-process-rule-names-true.snapshot, tests/__snapshots__/nested-rules/diff/source-rtl.snapshot, tests/__snapshots__/nested-rules/override/source-ltr-process-rule-names-true.snapshot, tests/__snapshots__/nested-rules/override/source-ltr.snapshot, tests/__snapshots__/nested-rules/override/source-rtl-process-rule-names-true.snapshot, tests/__snapshots__/nested-rules/override/source-rtl.snapshot, tests/css/input-nested.scss
This pull request implements the necessary algorith changes to the plugin to support [nested at-rules](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Nesting_at-rules). 
Previously, the plugin expected that declaration could be contained only in a rule. But with the relatively new [CSS Nesting Module](https://drafts.csswg.org/css-nesting-1/) it is possible to place declarations inside an at-rule. This is what MDM Documentation states:
Any [at-rule](https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule) whose body contains style rules can be nested inside another style rule using CSS nesting. Style rules nested inside at-rules take their nesting selector definition from the nearest ancestor style rule. Properties can be directly included inside a nested at-rule, acting as …
=> Support for nested at-rules

package.json, pnpm-lock.yaml, src/@types/index.ts, src/data/store.ts, src/index.ts, src/parsers/atrules.ts, src/parsers/keyframes.ts, src/parsers/rules.ts, src/utilities/keyframes.ts, src/utilities/rules.ts
This pull request solves a circular dependency between the rules and arRules parsers with a workaround storing the parsers in an object and passing this object around instead of importing the parsers.
>Note: as part of this merge request some dependencies have been updated
=> Remove circular dependency

CHANGELOG.md, src/utilities/selectors.ts
This pull request adds a check to verify if a rule has a `selectors` property before accessing it. For some reason it is impossible to reproduce this using a regular `CSS`, but if the `CSS` is created by `Tailwind`, some `Rules` don't have this property. (pretty similar to [this](https://github.com/elchininet/postcss-rtlcss/issues/110#issuecomment-993878002)). Instead of investigating why this occurs, it is better to add a check at the beginning and avoid the failure because it doesn't hurt to have it there.
```bash
[postcss] Cannot read properties of undefined (reading 'map')
```
=> Check if a Rule has a selectors property before accessing it

CHANGELOG.md, README.md, package.json, pnpm-lock.yaml, src/@types/index.ts, src/index.ts, tests/__snapshots__/logical-properties/combined/false.snapshot, tests/__snapshots__/logical-properties/combined/true.snapshot, tests/__snapshots__/logical-properties/diff/false.snapshot, tests/__snapshots__/logical-properties/diff/true.snapshot, tests/__snapshots__/logical-properties/override/false.snapshot, tests/__snapshots__/logical-properties/override/true.snapshot, tests/css/logical-properties.css, tests/logical-properties.test.ts
This pull request implements a new option to decide if the plugin should be executed using the `Once` or `OnceExit` visitors. 
This option defines which `PostCSS` visitor will be used to execute the plugin. By default it is `false`, so the `Once` visitor will be used. If it is `true`, `OnceExit` will be used instead. Setting this option in `true` is useful if the plugin is used together with [postcss-preset-env](https://www.npmjs.com/package/postcss-preset-env) because in those cases the plugin will be executed when `postcss-preset-env` finished all the CSS processing.
For example, let's assume that for the next example, `PostCSS RTLCSS` is executed together with `postcss-preset-env`.
```css
.test {
color: red;
border-inline-start-width: thick;
margin-inline-end: 5px; …
```
=> Implement a runOnExit option

src/utilities/rules.ts, src/utilities/selectors.ts, tests/__snapshots__/nested-rules/combined/source-ltr-process-rule-names-true.snapshot, tests/__snapshots__/nested-rules/combined/source-ltr.snapshot, tests/__snapshots__/nested-rules/combined/source-rtl-process-rule-names-true.snapshot, tests/__snapshots__/nested-rules/combined/source-rtl.snapshot, tests/__snapshots__/nested-rules/diff/source-ltr-process-rule-names-true.snapshot, tests/__snapshots__/nested-rules/diff/source-ltr.snapshot, tests/__snapshots__/nested-rules/diff/source-rtl-process-rule-names-true.snapshot, tests/__snapshots__/nested-rules/diff/source-rtl.snapshot, tests/__snapshots__/nested-rules/override/source-ltr-process-rule-names-true.snapshot, tests/__snapshots__/nested-rules/override/source-ltr.snapshot, tests/__snapshots__/nested-rules/override/source-rtl-process-rule-names-true.snapshot, tests/__snapshots__/nested-rules/override/source-rtl.snapshot, tests/css/input-nested.scss
This pull request fixes an issue related to multiple nested at-rules with rules in the middle. [This previous fix](https://github.com/elchininet/postcss-rtlcss/issues/492) was to avoid an error coming from Tailwind but that patch was not a fix in reality, it just hid the error. In this pull request, the management of multiple nested at-rules with rules in the middle has been fixed so the previous patch has been removed.
Closes: #520
=> Fix an issue with Tailwind and multiple at-rules
